-- AlterTable
ALTER TABLE `generation_job` ADD COLUMN `verify_engine` ENUM('CLAUDE', 'CODEX', 'ANTIGRAVITY') NOT NULL DEFAULT 'CLAUDE',
    ADD COLUMN `verify_warning` TEXT NULL,
    MODIFY `status` ENUM('RUNNING', 'VERIFYING', 'SUCCEEDED', 'FAILED') NOT NULL DEFAULT 'RUNNING';
